const quotes = [
"🙏 Bahagia itu sederhana: Hati yang penuh bersyukur",
"🌟 Dream Create Future",
"🌗 Dunia itu Bayangan, Akhirat itu Cahaya",
"🐇❌ Mengejar 2 Kelinci akan kehilangan keduanya",
"💰 Allah sebaik-baik Pemberi Rejeki",
"🌈 Setelah kesusahan pasti ada kemudahan",
"🚫 Maksiat = Penghalang Datangnya Rahmat Allah",
"🧠❌ Jalani bisnis jangan pakai akal, tapi pakai iman",
"🚪 Allah akan memberikan jalan bagi hamba yang takwa",
"🤝 Sebaik-baik manusia adalah yang bermanfaat bagi sesama",
"🦋 Jangan kejar kupu-kupu, buatlah kebun, nanti datang sendirinya",
"🧭 Jika Allah ridho, hidupmu akan tertata",
"⚔️ Jihad terbesar = Melawan hawa nafsu",
"🙊 Jangan keluhkan hidupmu, salahkan malasmu",
"🕌 Qobliyah Subuh = Penakluk Dunia",
"📿 Allahumma Faqihna Fiddin",
"💸 Hidup itu murah, yang mahal gengsi",
"🧠 Orang Pintar kalah dengan Orang Beruntung",
"💪 Pengen mulya kudu wani rekoso, kuat ngelawan goda",
"🏆 Kesuksesan bukan dari kepandaian, tapi dari rahmat Allah",
"🎯 Cepat sukses = Ridho orang tua",
"💖 Tidak berkurang harta yang disedekahkan, malah bertambah",
"💪 Setiap orang sedang berjuang dengan ujiannya masing-masing",
"❤️‍🔥 Qolbun Syakur = Hati yang selalu bersyukur",
"👨‍👩‍👧 Jadilah orang tua yang berkualitas",
"🛐 Perbaiki sholatmu, Allah akan perbaiki hidupmu",
"⚡ Tidak ada musibah tanpa didahului dosa",
"🕋 Ya Sayyidi Ya Rosulallah Khud Biyyadi Qolat Hillati Adrikni",
"🗝️ Kunci doa = yakin terkabul 💪",
"🪄 Kunci sukses: Bekti Wong Tuo, Mertuo & Guru",
"🤲 Ya Allah berikan Hidayah, Taufiq & Ridho-Mu",
"🧘‍♂️ Kunci kemuliaan ada di hati yang nerimo",
"🛠️ Apapun masalahmu = Benahi dulu sholatmu",
"🛤️ Istiqomah = Sukses yang langgeng",
"🧠✨ Hal besar dicapai dengan cara yang tak logis & matematis",
"🚫 Mustahil Allah membawamu sejauh ini hanya untuk gagal",
"💰 Cara cepat kaya = Bersyukur ala kulli hal",
"🏡 Memuliakan tamu = Memperlancar rejeki",
"⛵ Perahu aman di dermaga, tapi bukan itu tujuan dibuat",
"💸 Boroslah dalam sedekah, biarkan uang panggil temannya",
"🌞 Datangi cahaya, bayangan akan di bawah kakimu",
"🚫 Ya Allah hilangkan semua kesempatan untuk bermaksiat",
"📦 Rejeki sudah tertakar, tidak akan tertukar",
"🐃 Hawa nafsu = Sifat hewan & ujian dari Allah",
"🙇‍♂️ Ya Allah, aku tidak mau lelah cari hartamu, tapi ingin lelah bagi-bagi rejeki-Mu",
"🕌 Goal bisnis bukan hanya cari uang, tapi juga bangun tim yang ngaji & dzikir",
"💥 Ujian hawa nafsu = Tanda akan datang rejeki besar",
"📜 Takdir milik Allah, doa & usaha milik kita",
"📣 Alhamdulillah ’ala kulli hal",
"😊 Bahagia itu sederhana, bersyukur atas yang kamu miliki",
"📖 Berdoalah kepada-Ku niscaya akan Ku-kabulkan doamu (QS Ghafir:60)",
"🌊 Tetap tenang, kuasai ombak – Calm down, ride the wave",
"💼 Niat kerja: cari ridho Allah agar diberi kemudahan & kecukupan",
"🧘‍♀️ Kita terlalu banyak meminta, kadang lupa bersyukur atas tubuh yang sehat",
"🧠 Hakikat hidup adalah pengendalian diri",
"🙈 Dosa = Penghalang terkabulnya doa",
"🕋 Segala sesuatu jika tidak diniati ibadah, maka hasilnya hanya dunia",
"🌌 Doa setelah tahajud = Anak panah yang tepat sasaran",
"✨ Kita tidak akan pernah tahu rencana Allah, selalu husnudzon",
"⛔ Dosa bisa menghalangi rejeki",
"🔥 Kalau mimpimu besar, usahamu tak boleh kecil",
"👨‍👩‍👦 Warisan anak bukan harta, tapi orangtua yang sehat",
"🧠 Bisnis itu soal mental, dunia ini milik para pemberani",
"⏳ Hidup itu pilihan, waktu akan terus berkurang",
"🛏️ Jika kamu tidak menemukan cara menghasilkan uang saat tidur, maka kamu akan kerja seumur hidup",
"🎁 Sukses itu bonus, tugas kita adalah ikhtiar dan cari ridho Allah",
"🥚 Jangan taruh semua telur dalam satu keranjang",
"😈 Musuh paling menakutkan = Hawa nafsu bermaksiat",
"🛡️ Hasbunallah wa ni’mal wakil – Cukuplah Allah sebagai penolong",
"😓 Lelahlah dalam ketaatan, karena surga tidak dikelilingi kenyamanan",
"🚶‍♂️ Hidup bukan soal siapa yang cepat, tapi siapa yang istiqomah",
"🌌 Jangan remehkan dirimu — bisa jadi doa 1/3 malam mengalahkan rencanamu seumur hidup",
"📦 Rejeki bukan ditunda, tapi akan datang di waktu yang tepat",
"🙏 Alhamdulillah ya Allah, aku sangat bersyukur dan bahagia",
"🧲 Aku adalah magnet uang, semakin banyak uang datang kepadaku",
"🤲 Robbi inni dzolamtu nafsi faghfirli",
"📈 Bismillah, omset bulan ini 2 Milyar, aamiin YRA",
"🕊️ Alhamdulillah ya Allah, terima kasih atas segala Nikmat & Rahmat-Mu",
"😭 Percuma Omset Besar kalo tidak Berkah & Toyyib",
"❌ Maksiat dan Kaya tidak bisa bersatu, Pilih salah satu",
"🚀 Nothing is Easy but Nothing is impossible",
"🚀 Yakinlah Jika Allah sudah ikut Andil maka Tidak ada yang Mustahil",
"⚔️ If you know the enemy and know yourself, you will win of a hundred battles",
"🤜 Strategi tanpa Cara = Jalan paling lambat untuk Menang, Cara tanpa Strategi = Teriakan menuju Kekalahan",
"😛 Lidah yg tergigit saat makan  bukti bahwa kamu bisa gagal meskipun pengalaman puluhan tahun",
"💬 Kalo ada yang ngomongin kita dibelakang, berarti kita lagi didepan",
"😮‍💨 Lelah itu pasti, tapi menyerah bukan solusi",
"🤲 Manusia Punya Kendala, tapi Allah Punya Kendali",
"🌤️ Apapun yang terjadi hari ini pada kita itu pasti yang terbaik",
"👁️‍🗨️ Seandainya manusia bisa melihat takdirnya, maka mereka akan ridho dengan takdirnya",
"💸 Cobaan yang paling ringan itu tidak punya uang",
"🤑💃 Cobaan yang paling berat itu uang banyak dan digoda wanita cantik",
"🔺 Target Hari ini adalah mengalahkanmu yang kemarin",
"⚔️ Samurai yang tajam dibuat dari besi yang dibakar dan dipukul – dan itulah prosesnya",
"🌊 Pelaut yang hebat lahir dari ombak besar dan badai yang ganas",
"🌧️🌈 Setelah hujan dan badai, pasti ada pelangi",
"🕌 Sesungguhnya bersama kesulitan ada kemudahan (QS. Al-Insyirah: 5–6)",
"💡 1 Kesulitan mustahil mengalahkan 2 Kemudahan",
"🙏 Dan barangsiapa yang bertawakkal kepada Allah, niscaya Allah akan mencukupkan (keperluan)nya. (QS. Ath-Tholaq: 3)",
"⚓ Pelaut yang handal tidak dilahirkan oleh laut yang tenang",
"📈 Kualitas manusia tergantung pada tahap kehidupan yang dijalani",
"🧠🔥 Kontrol emosimu — jika kamu emosi pada orang lain, maka mereka punya kontrol padamu",
"🌿 Imun Booster = 🍋 Lemon, 🍯 Madu, 🌴 Kurma, 🌶️ Jahe, 🥛 Yogurt, 🧄 Bawang Putih Bakar",
"🩺 Kepanikan adalah separuh penyakit, 😌 Ketenangan adalah separuh obat, 🕊️ Kesabaran adalah permulaan kesembuhan",
"💼 Sukses bukan hanya kerja keras 💪, tapi juga soal ✨ afirmasi dan 💰 memahami sifat uang",
"⚡ PERUBAHAN NASIB hanya akan kita alami jika kita BERANI melakukan hal yang BERBEDA 🔥",
"👦 Anak di pondok menjadi 💝 sumber rejeki untuk 👨‍👩‍👧 orang tuanya",
"⏰ Ujian datang ketika ada adzan – godaan setan untuk menunda salat 🕌",
"💸 Jika rezeki hanya soal kerja keras, tukang becaklah yang paling kaya. Rezeki itu rahmat Allah 🤲",
"🕊️ Cari rezeki bukan karena jumlahnya, tapi karena berkahnya 🌿",
"🏃‍♂️ Rezeki itu sifatnya mengejar, bukan dikejar. Ia mendatangi orang yang tawakal 🌟",
"🌊 Sawang sinawang – orang yang merasa kurang sebenarnya kurang bersyukur 🙏",
"🤲 Allah suka dengan hamba yang selalu datang berdoa kepada-Nya 💖",
"💳 Orang yang berhutang itu tidak yakin bahwa besok ada pertolongan dari Allah, padahal Allah Maha Pemberi Cukup 🌙",
"🚪 Kesempatan tidak datang dua kali. Yang terlambat hanya akan menyesal 😔",
"🌅 Momentum itu seperti matahari terbit, kalau terlambat bangun, kamu akan kehilangannya 🌞",
"💡 Ide hanya bernilai ketika dieksekusi. Menunda = kehilangan peluang 🔑",
"⏳ Yang menunggu waktu tepat, justru sering kehilangan waktu terbaik 🕰️",
"⚡ Momentum datang sebentar, lalu pergi tanpa kabar. Yang berani ambil segera = pemenang 🏆",
"😴 Setiap menit bermalas-malasan adalah utang yang dibayar dengan penyesalan 🥀",
"🌅 Sholat Dhuha adalah pembuka rezeki, 🌞 Cahaya yang menuntun hati pada petunjuk dan jalan dari setiap masalah.",
"🕰️ Kerja hanya selingan untuk menunggu waktu Sholat.",
"📖 Jika Allah menolongmu, tidak ada yang bisa mengalahkan-Nya. Tapi jika Allah tidak menolong, maka tidak ada penolong lain selain Dia – Al Imran 160.",
"🤲 Disaat terjatuh, kembalilah pada Allah. 💨 Percayalah begitu mudah Allah membalikkan sesuatu sampai dunia 🌍 lari mengejarmu.",
"💰 Orang yg tidak bisa manage uang pribadi, maka dia tidak bisa manage uang bisnis – Pak Win.",
"📌 Prinsip Keuangan = No 1 JANGAN HUTANG!! 💳 No 2 GAYA HIDUP HARUS SAMA meski income naik.",
"⚠️ Hutang = JEBAKAN UANG – Seolah-olah uang kita banyak 💸 tapi justru ganggu cashflow.",
"💪 Lebih baik capek saat muda 👦 daripada saat tua 👴, karena tenaga & otak sudah berbeda.",
"⚡ Perfeksionis akan kalah dengan orang yang action cepat 🚀 untuk menuju sukses.",
"⏳ Waktu tidak bisa dibalik. Jangan sampai menyesal di masa tua karena muda tidak mau kerja keras.",
"💎 Kekayaan itu datang pada orang yang tahan tekanan paling lama – Pak Win.",
"🍜 Banyak bisnis tidak menjadi kaya. Antoni Salim hanya fokus jualan Indomie dan punya profit 10 trilyun setahun.",
"👶 MUDA = usia produktif, 👴 TUA = usia pensiun.",
"🚰 ORANG PIPA BOCOR = tidak bisa manajemen, tidak mikir jangka panjang, berapapun uang habis",
"🌳 Semakin tinggi pohon, semakin besar angin",
"🙈 Monyet tidak akan jatuh terkena badai, tp jatuh karena angin sepoi2 yang melenakan",
"🤲 Ikhtiar itu syariat, Sukses itu kehendak Allah, Manusia punya ikhtiar, Hasil milik Allah",
"☁️ Langit tegak tanpa tiang, laut tenang tanpa pagar, burung cari makan tanpa peta, semuanya tetap berjalan",
"🔥 Bisnis itu mental dulu baru ilmu, carilah hobi yg butuh keberanian & menantang mental",
"💭 Kadang kita merasa kekurangan, tapi sebenarnya kita yang tidak pernah merasa cukup dan kurang bersyukur",
"🌟 HIDUP JGN SEDERHANA, Hidup itu harus hebat, luas, kuat, besar dan bermanfaat. Yg SEDERHANA sikapnya",
"💼 Teken Tekun Tekan - Pegang, Konsisten, Tercapai",
"🧩 Seng Ono Seng iso Lakokno",
"🏆 Wong seng Temen Bakal Tinemu - Manjadda Wajada",
"💪 Kelihatannya Tidak Mudah tapi insyaallah BISA 💪",
"😔 Mungkin ada dosa yang membuat rejeki ini tertahan",
"💫 Rahasia Frekuensi Rejeki = Bukan produk yg sulit laku, tp hati kita blm ikhlas dan pasrah, bersihkan hati, pasrah dan yakin",
"🌱 Ekonomi boleh sulit, tapi hati jangan ikut sempit. Karna sulit adalah cara tercepat dekat dengan Allah",
"🕋 Bukan Allah yg nggak ngabulin, tapi Kita yang ngg mau Doa",
"🤝 Sedekah menarik keberuntungan - Keberuntungan mendatangkan rejeki",
"⚖️ Bukan soal siapa yang cepat, tp siapa yg dipilih Allah. Kemampuan + Kesempatan = Keberuntungan"
];